### ISSUE TITLE
How to prefix routes?

### ISSUE THREAD

**Issue by theogravity** [carlansley/swagger2-koa#12]
is there a way to define a prefix for routes?

eg I have everything under a `/user` route and all the items I define under that route would prefix with `/user`.

Also, multiple router / prefixes , eg `/user`, `/posts`?

**Comment by carlansley** [comment]
You can set the `basePath` for all the paths in your swagger file, if that's what you mean?

Also check out koa-mount if you need multiple APIs/swagger files to be mounted under different paths.

**Comment by theogravity** [comment]
Ah, didn't know it read off of that. Thanks.
