### ISSUE TITLE
Validating header in validate.ts

### ISSUE THREAD

**Issue by andy-yeung-cx** [carlansley/swagger2-koa#15]
Hi just wonder in validate.ts.  
const validationErrors = swagger.validateRequest(compiledPath, context.method, context.request.query, context.request.body)

Could the library add context.request.header at the end? Now it complains the request schema not match if I mark a header parameter as compulsory.

**Comment by carlansley** [comment]
Yes for sure.  Not something I've needed yet but happy to accept a PR on this, especially if you can add a test for it.

**Comment by brad-jones** [comment]
FYI: I sneaked this into my PR here: https://github.com/carlansley/swagger2-koa/pull/17
