### ISSUE TITLE
Document not exposed after using swaggerRouter

### ISSUE THREAD

**Issue by damianb** [carlansley/swagger2-koa#19]
As on tin - the example provided in the readme for the "UI" middleware (which looks like it'd be nice to be able to use) is sadly not possible as "document" itself is not directly exposed.  We'd have to resort to calling swagger.loadDocumentSync ourselves, which honestly should not be necessary.

**Comment by carlansley** [comment]
To avoid loading the document twice, you can pass the document object to the router.  So, 1) load document, 2) create router (using document), 3) add UI middleware (using same document object).

**Comment by damianb** [comment]
I getcha - the example still should probably be looked at, though.  We have `document` which comes out of nowhere with unknown content, which might be best as its own example.
