### ISSUE TITLE
number inputs for numeric path parameters not being considered valid

### ISSUE THREAD

**Issue by damianb** [carlansley/swagger2-koa#20]
As on tin.

Requesting the following...

    http://localhost:9990/api/v1.0/post/1

...which is defined as...

``` yml
swagger: "2.0"
info:
  version: "1.0"
  title: "thing"
basePath: "/api"
schemes:
- "http"
paths:
  /v1.0/post/{id}:
    get:
      tags:
      - "post"
      summary: "Gets a post"
      description: ""
      operationId: "getPost"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        # FIXME: https://github.com/carlansley/swagger2-koa/issues/20
        type: "integer"
        format: "int64"
        # type: "string"
        description: "The post to fetch."
        required: true
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
```

This is currently failing with the following:

    {"code":"SWAGGER_REQUEST_VALIDATION_FAILED","errors":[{"actual":"{id}","expected":{"type":"number"},"error":"data is the wrong type","where":"path"}]}

...Which is pretty far from the case, since {id} *is* a numeric input in this case.

Changing the type to "string" in the swagger file results in validation passing, which is not a desirable workaround.

**Comment by carlansley** [comment]
This is related to a recent PR that added path validation.  lmk if 0.0.39 fixes this issue for you.

**Comment by damianb** [comment]
Negative, still occurring.   Same swagger file, same URI - `{id}` should be coming in as `1`, but is failing the check.

```
        type: "integer"
        format: "int32"
```

    {"code":"SWAGGER_REQUEST_VALIDATION_FAILED","errors":[{"actual":"{id}","expected":{"type":"integer","format":"int32"},"where":"path"}]}

```
        type: "number"
```

    {"code":"SWAGGER_REQUEST_VALIDATION_FAILED","errors":[{"actual":"{id}","expected":{"type":"number"},"where":"path"}]}

```
$ yarn list | grep swagger
├─ swagger-ui@2.2.10
├─ swagger2-koa@0.0.39
│  ├─ swagger-ui@^2.2.10
│  └─ swagger2@^0.0.27
├─ swagger2@0.0.27
```


Out of curiosity, *should* value itself be displaying as `{id}`?  Looking at [this](https://github.com/carlansley/swagger2/blob/107d0199c023d160f82c070329d1fe2b3fe160f7/src/validate.ts#L48) I kinda wonder if it should be the actual value of `1`...
