### ISSUE TITLE
Exporting routes from a controller

### ISSUE THREAD

**Issue by rickardrosen** [carlansley/swagger2-koa#21]
Hi,
I'm looking to implement this module for a project, but I'm not sure how I would go about splitting up my project in separate controllers.
Normally I would export a router from the controller and use the routes().

Is this possible somehow with the swaggerRouter?

Thanks!

**Comment by carlansley** [comment]
The router is designed to be a quick/simple way of getting up and running.  If your needs are more complex, you may want to use the validate etc middleware directly.

**Comment by rickardrosen** [comment]
Yes, figured as much by looking at the module code.
Probably should have done so before raising a ticket. =)

I'll carry on with your suggestion.

Thanks!

**Comment by carlansley** [comment]
In our project structures, to support semver on our APIs, we organize the code:
```
src/api/index.ts
       /v1/index.ts
          /swagger.yml
          /some-route.ts
          /another-route.ts
          /...
       /v2/index.ts
          /swagger.yml
          /some-more-routes.ts
          /...
```

Apply swagger2-koa to each version of the API and then we koa-mount everything together as a single web-app. (with v1/, v2/ etc paths)

**Comment by carlansley** [comment]
One other trick you may find useful- we use `sw2dts` to generate typescript definitions from each swagger file (creating a `swagger.ts` for each `swagger.yml`) which allows us to type directly off the swagger files themselves in our API code.
