### ISSUE TITLE
Update to node 16/es2022, remove swagger-ui

### ISSUE THREAD

**Issue by carlansley** [carlansley/swagger2-koa#56]

**Comment by carlansley** [comment]
The version of swagger-ui is old and full of security issues.  Eliminating the functionality as it is best served via other methods at this point.

**Comment by toresbe** [comment]
Could you please suggest some other methods?

**Comment by carlansley** [comment]
I'd suggest the plugin(s) that come with the IDE of your choice.  e.g. the ones for Jetbrains/Intellij/Webstorm and VS Code are really good now.

**Comment by toresbe** [comment]
Thanks! :)

**Comment by isaacgarc-dev** [comment]
The swagger UI took me by surprise.  Thanks for suggesting other options.
