### ISSUE TITLE
Support multiple middle-ware for each http verbs in the router

### ISSUE THREAD

**Issue by elizar** [carlansley/swagger2-koa#8]
This feature would be nice to have. It makes it easier to add custom filter-like middle-wares for route handlers.

**Comment by carlansley** [comment]
Just so I understand fully, can you give some example code of how you want to use it?

**Comment by elizar** [comment]
This is from koa-router example:

```
router.get(
  '/users/:id',
  function (ctx, next) {
    return User.findOne(ctx.params.id).then(function(user) {
      ctx.user = user;
      return next();
    });
  },
  function (ctx) {
    console.log(ctx.user);
    // => { id: 17, name: "Alex" }
  }
);
```

**Comment by elizar** [comment]
This is awesome!

Thanks @carlansley 👍

**Comment by carlansley** [comment]
np, thx for reporting the issue!
