### ISSUE TITLE
Two issues of the path validation

### ISSUE THREAD

**Issue by ctc316** [carlansley/swagger2-koa#9]
1. Beginning Slash Issue
--> When basePath is set to root, e.g. "/", the path validation will be not found all the time because regex would start from double slash like "//v1/something".  It can be solved by simply remove basePath,  but it would be great I can have the basePath to be "/" on the document.

2. End Slash Issue 
--> When path is, for example, "/v1/something", I cannot request for "/v1/something/", and vice versa. It would be great to adapt these two kinds of request format.

**Comment by carlansley** [comment]
Thanks for the contribution!
